/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package clases;

public class Main {

	public static void main(String[] args) {
		Persona persona= new Persona("Kimi","fdf",20);
		MiniList list= new CList();
		list.add(persona);
		if(list.get(0)==persona) {
			System.out.println("eefe");
		}
	}
}
